name: MinedaeronItems
version : 0.1
main: MinedaeronItems.main
author: Falcort
website: http://thibaultsouquet.fr/
description: This plugin is design to create custom items
commands:
  sword:
    description: sword pour la liste, sword plus le nom pour l'item
    usage: /sword
  axe:
    description: axe pour la liste, axe plus le nom pour l'item
    usage: /axe